### ISSUE TITLE
怎么理解 free_list 呢？

### ISSUE THREAD

**Issue by chinesehuazhou** [zpoint/CPython-Internals#18]
怎么直观地看到一个对象被重复使用了呢？

例如：
a = list()
id(a) 
del a
b = list()
id(b)

按照这个执行顺序，我本理解为 id(a) == id(b)，但事实上并没有。
被 del 的那个对象怎样会被重复利用呢？

**Comment by zpoint** [comment]
@chinesehuazhou 

    $ cat free_list.py 
    a = list()
    id(a)
    del a
    b = list()
    id(b)

dis 模块处理后的结果 `python3 -m dis free_list.py`

      1           0 LOAD_NAME                0 (list)
                  2 CALL_FUNCTION            0
                  4 STORE_NAME               1 (a)

      2           6 LOAD_NAME                2 (id)
                  8 LOAD_NAME                1 (a)
                 10 CALL_FUNCTION            1
                 12 POP_TOP

      3          14 DELETE_NAME              1 (a)

      4          16 LOAD_NAME                0 (list)
                 18 CALL_FUNCTION            0
                 20 STORE_NAME               3 (b)

      5          22 LOAD_NAME                2 (id)
                 24 LOAD_NAME                3 (b)
                 26 CALL_FUNCTION            1
                 28 POP_TOP
                 30 LOAD_CONST               0 (None)
                 32 RETURN_VALUE

这5行代码对应到了 17 个 python 字节码, 每个字节码又是一部分 C 代码, 比如 `CALL_FUNCTION`

    case TARGET(CALL_FUNCTION): {
        PREDICTED(CALL_FUNCTION);
        PyObject **sp, *res;
        sp = stack_pointer;
        res = call_function(&sp, oparg, NULL);
        stack_pointer = sp;
        PUSH(res);
        if (res == NULL) {
            goto error;
        }
        DISPATCH();
    }

那么是否有这种可能比如 `call_function` 里面的函数创建了几十个临时的新的 list, 之后进行释放, 此时这些临时的 list 就填充到了 free_list 里, free_list 是一个后进先出的结构, 所以在删除 a 和创建 b 中间, 只要解释器在你看不到的地方额外释放多一个 list, 那么你创建 b 的时候取的会是最后插入 free_list 的元素, 他们的 id 就不会相同

特别是你在交互式的环境下, 读取你本行的输入, 翻译成字节码, 执行字节码, 输出, 再读取下一行输入的循环中, 会有更大的概率创建更多的 list 对象

我没有去调试看在你删除和创建的过程中解释器在什么位置又创建/删除了 list

如果你想看到相同的 id, 可以一次多创建几个

    a = [[] for i in range(10)]
    print(id(a))
    for i in range(len(a)):
        print(id(a[i]))
        a[i] = 1
    del a
    print("after del")
    b = [[] for i in range(10)]
    print(id(b))
    for i in range(len(b)):
        print(id(b[i]))

运行结果

    4407156552
    4407156616
    4409118920
    4408367560
    4409077576
    4409077512
    4409077256
    4407979208
    4409077640
    4409148616
    4409148680
    after del
    4407156552
    4409148680
    4409148616
    4409077640
    4407979208
    4409077256
    4409077512
    4409077576
    4408367560
    4409118920
    4407156616

下面的 id 大致上是按照上面的 id 的倒叙取的, 不完全按照是因为前面说的原因的影响

最开始在 list 对象介绍中写的就是一次创建和释放多个 list 的示例代码, 但是有童鞋反应难以理解, 所以才写成现在这样一看就能理解的方式~

**Comment by chinesehuazhou** [comment]
应该是这个原因。多创建几个后，果然命中率就上来了。（70%）
我用的 IPython 调试，也没运行别的程序，很奇怪为何会有额外的消耗？

**Comment by zpoint** [comment]
写 IPython 的人创建/释放的列表, 不是你创建/释放列表

输入一行代码, 敲击回车 -> 读取你的文本代码 -> 编译成字节码 -> 执行对应的字节码 -> 打印执行结果

比如编译的时候可能用列表存储词法分析的结果, 或者执行字节码的时候创建了额外的列表用来存储字节码参数, 或者执行完成的时候可能创建了列表存储一些临时变量用作其他计算统计, 再打印出执行结果返回给你(只是打个比方)
