### ISSUE TITLE
tp_getattro 的分析存在问题

### ISSUE THREAD

**Issue by Hanaasagi** [zpoint/CPython-Internals#19]
https://github.com/zpoint/CPython-Internals/blob/master/Interpreter/descr/descr_cn.md

在 `descr` 章节中有

- `tp_getattro` 在 c 里面表示 `__getattribute__` 方法

- `tp_getattr` 在 c 里面表示 `__getattr__` 方法

其实这里是不正确的，参考文档 https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_getattr

> 
> An optional pointer to the get-attribute-string function.
> 
> This field is deprecated. When it is defined, it should point to a function that acts the same as the `tp_getattro` function, but taking a C string instead of a Python string object to give the attribute name. The signature is

这个两个应该是指向作用相同的函数，不同之处是一个接受 `PyUnicodeObject`，另一个接受 C 的字符串。至于 `__getattribute__` 和 `__getattr__`，这个是在 `type_new` 的时候将 `tp_getattro` 指向了 `slot_tp_getattr_hook`

**Comment by zpoint** [comment]
@Hanaasagi 已修改, 感谢指正♪(･ω･)ﾉ
