### ISSUE TITLE
Markdown code formatting

### ISSUE THREAD

**Issue by cleoold** [zpoint/CPython-Internals#26]
Thanks for your brilliant guide. However I noticed in your files, the referenced source codes are laid out like this:
### ...

the **PyMethodObject** delegate the real call to **im_func** with **im_self** as the first argument

    static PyObject *
    method_call(PyObject *method, PyObject *args, PyObject *kwargs)
    {
        PyObject *self, *func;
        /* get im_self */
        self = PyMethod_GET_SELF(method);
        if (self == NULL) {
            PyErr_BadInternalCall();
            return NULL;
        }
        /* get im_func */
        func = PyMethod_GET_FUNCTION(method);
        /* call im_func with im_self as the first argument */
        return _PyObject_Call_Prepend(func, self, args, kwargs);
    }

 
It is somehow more clear to use the ``` syntax like this (see raw text):
### ...

the **PyMethodObject** delegate the real call to **im_func** with **im_self** as the first argument
```c
    static PyObject *
    method_call(PyObject *method, PyObject *args, PyObject *kwargs)
    {
        PyObject *self, *func;
        /* get im_self */
        self = PyMethod_GET_SELF(method);
        if (self == NULL) {
            PyErr_BadInternalCall();
            return NULL;
        }
        /* get im_func */
        func = PyMethod_GET_FUNCTION(method);
        /* call im_func with im_self as the first argument */
        return _PyObject_Call_Prepend(func, self, args, kwargs);
    }
```

So we can have the proper syntax highlighting for each language and avoid being confused seeing the plain text. This is standard in Github markdown. What is your opinion?

**Comment by zpoint** [comment]
@cleoold Thanks for your tips, I don't know the syntax highlight for Markdown before
 
I've written a script to add the syntax highlight for every readme file, However It needs time to make sure the script works for every readme file, I will merge the scripts' change first, and leave the check work later.
