### ISSUE TITLE
Cython GIL - check_interval & interval

### ISSUE THREAD

**Issue by Panlq** [zpoint/CPython-Internals#27]
最近在看Python3.8.3的源码，参照您的分析有一个疑惑。
但是还有一个check_interval参数是，初始化的时候是被设置成100，这个参数看解释是将异步事件检查间隔设置为n条指令。**且也会影响线程的切换，没理解这个参数和gil.interval 二者的关系？ check_interval 难道就是那个tick吗？ 望解答，感谢。**

 初始化
Python3.8.3/Python/pystate.c  line： 207 `interp->check_interval = 100;`

Python-3.8.3/Python/sysmodule.c
```c
/*[clinic input]
sys.setcheckinterval

    n: int
    /

Set the async event check interval to n instructions.

This tells the Python interpreter to check for asynchronous events
every n instructions.

This also affects how often thread switches occur.
[clinic start generated code]*/

static PyObject *
sys_setcheckinterval_impl(PyObject *module, int n)
/*[clinic end generated code: output=3f686cef07e6e178 input=7a35b17bf22a6227]*/
{
    if (PyErr_WarnEx(PyExc_DeprecationWarning,
                     "sys.getcheckinterval() and sys.setcheckinterval() "
                     "are deprecated.  Use sys.setswitchinterval() "
                     "instead.", 1) < 0)
        return NULL;

    PyInterpreterState *interp = _PyInterpreterState_Get();
    interp->check_interval = n;
    Py_RETURN_NONE;
}
```

**Comment by zpoint** [comment]
[tick](https://github.com/zpoint/CPython-Internals/blob/master/Interpreter/gil/gil_cn.md#python32-%E4%B9%8B%E5%89%8D%E7%9A%84%E7%BA%BF%E7%A8%8B%E5%88%87%E6%8D%A2) 机制是 python 3.2 之前才使用的

check_interval: 100 表示每隔100个虚拟机指令之后检查一下

而 python 3.2 以后的版本就不是这个机制了, 在3.8版本的代码中保留了 check_interval 应该是为了向下兼容(比如下面这个函数), 但是线程切换的时候用的是新的策略, 以 _gil_runtime_state->interval 为准, 具体在 [这里](https://github.com/zpoint/CPython-Internals/blob/master/Interpreter/gil/gil_cn.md#python32-%E4%B9%8B%E5%89%8D%E7%9A%84%E7%BA%BF%E7%A8%8B%E5%88%87%E6%8D%A2) 用到

```python3
sys.getcheckinterval()
/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py:1: DeprecationWarning: sys.getcheckinterval() and sys.setcheckinterval() are deprecated.  Use sys.getswitchinterval() instead.
  '''
```
综上

check_interval 指的确实是 tick, 代码中保留这个变量但是没有作用
interval 指的是当前的线程需要等待多少毫秒之后把 gil_drop_request 设置成 1, 有作用

**Comment by Panlq** [comment]
原来，我也是看到没地方调用**check_interval**，所以有疑惑，
用python调用`sys.getcheckinterval() `就是100，目前来看确实如您所说，应该是为了向下兼容。
谢谢，看您的文章收获很大。
