### ISSUE TITLE
图错误

### ISSUE THREAD

**Issue by qiaobz** [zpoint/CPython-Internals#44]
https://github.com/zpoint/CPython-Internals/blob/master/BasicObject/dict/dict_cn.md

有几个图好像有点小错误，
```
# 注意, dk_usable 和 dk_nentries 现在变了
d[0] = "value0"
```
后面示例图是 `3 "value3"`

**Comment by zpoint** [comment]
应该是 
```python3
d[0] = "value3"
```
改过来了，谢谢
