### ISSUE TITLE
Interpreter/frame/frame_cn.md code->nfrees变量名问题

### ISSUE THREAD

**Issue by RyanHe123** [zpoint/CPython-Internals#45]
https://github.com/zpoint/CPython-Internals/blob/master/Interpreter/frame/frame_cn.md#f_valuestackf_stacktopf_localsplus

Line 68: 
code->nfrees: 自己是内嵌函数的情况下, 包含了外部函数和自己同时用到的变量名称

这里的`code->nfrees`是否应为`code->co_freevars`?

**Comment by zpoint** [comment]
@RyanHe123 已改正, 感谢, 细心👍
