### ISSUE TITLE
Interpreter/frame/frame_cn.md 图片解释疑问

### ISSUE THREAD

**Issue by RyanHe123** [zpoint/CPython-Internals#46]
![](https://github.com/zpoint/CPython-Internals/raw/master/Interpreter/frame/example3.png)
这个原文中的解释是：
> 字段 f_lasti 现在值是 36, 表明他在 38 YIELD_FROM 之前

但是如果这样分析的话，运行了`36 LOAD_CONST 0 (None)`但是没运行`38 YIELD_FROM`时，栈顶指针`stacktop`应该指向None下面的位置，而不是指向`None`。

我认为有两种解释方式：
1. 图存在错误，`stacktop`指针指向None下面的`2`的位置
2. 解释存在错误，该图并不是运行完36而没有运行38，而是已经运行完38的图，因为YIELD_FROM需要多次运行，所以在cevel.c中，YIELD_FROM指令的结尾`f->f_lasti -= sizeof(_Py_CODEUNIT);`，将f->f_lasti保持不变，保证在下次运行的时候会再次调用`38 YIELD_FROM`，此时的None已经在YIELD_FROM指令中弹出了，所以与图片是相符的。

**Comment by zpoint** [comment]
是2, 已修正, 感谢指正
