### ISSUE TITLE
建议代码第一行标出文件名及其路径

### ISSUE THREAD

**Issue by kkxue** [zpoint/CPython-Internals#56]
如题

**Comment by kkxue** [comment]
如果同意的话，我也可以加

**Comment by zpoint** [comment]
如果可以的话需要你帮忙加, 暂无精力继续更新, 感谢🙏

**Comment by kkxue** [comment]
提交了个PR，确认下格式：https://github.com/zpoint/CPython-Internals/pull/58
如果没有问题，后面就按照这样来
